# The following tests use the Rest Client VSCode extension
# as an alternative to Postman.  The repo can be found here:
# https://github.com/Huachao/vscode-restclient

@hostname = localhost
@port = 5000

@server = http://{{hostname}}:{{port}}

### TEST SANITY CHECK AND REBRICKABLE ENDPOINT FIRST
GET {{server}}/sanityCheck

###

# Bouncing request off of rebrickable API to test key
GET https://rebrickable.com/api/v3/lego/colors/
Authorization: key {{bricks_key}}

### BEGIN USER ENDPOINT TESTING
@user_id = enter user id here to test user endpoints

POST {{server}}/api/users
Content-Type: application/json

{
  "name": "Joe Doe",
  "email": "joe@email.com",
  "password": "12345"
}

###

GET {{server}}/api/users
Content-Type: application/json

###

GET {{server}}/api/users/{{user_id}}
Content-Type: application/json

###

DELETE {{server}}/api/users/{{user_id}}
Content-Type: application/json

### END USER ENDPOINT TESTING