# The following tests use the Rest Client VSCode extension
# as an alternative to Postman.  The repo can be found here:
# https://github.com/Huachao/vscode-restclient

@hostname = localhost
@port = 5000

@server = http://{{hostname}}:{{port}}

GET {{server}}/sanityCheck

###

# Bouncing request off of rebrickable API to test key
GET https://rebrickable.com/api/v3/lego/colors/
Authorization: key {{bricks_key}}

### Actual app endpoints below this line

POST {{server}}/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jd@email.com",
  "password": "12345"
}

###
@user_id = 'enter a user id here'
GET {{server}}/api/users/{{user_id}}
Content-Type: application/json