# The following tests use the Rest Client VSCode extension
# as an alternative to Postman.  The repo can be found here:
# https://github.com/Huachao/vscode-restclient

@hostname = localhost
@port = 5000

@server = http://{{hostname}}:{{port}}

### TEST SANITY CHECK AND REBRICKABLE ENDPOINT FIRST
GET {{server}}/sanityCheck

###

# Bouncing request off of rebrickable API to test key
GET https://rebrickable.com/api/v3/lego/colors/
Authorization: key {{bricks_key}}

### BEGIN USER ENDPOINT TESTING

# @user_id = ***ENTER USER ID HERE AS REQUIRED***
# @token = ***ADD A VALID TOKEN TO TEST PROTECTED ENDPOINTS***

POST {{server}}/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@email.com",
  "password": "12345"
}

###

GET {{server}}/api/auth
Content-Type: application/json
X-Auth-token: {{token}}

###

GET {{server}}/api/users/{{user_id}}
Content-Type: application/json

###

PUT {{server}}/api/users/{{user_id}}
Content-Type: application/json

{
  "email": "updated@email.com"
}

###

DELETE {{server}}/api/users/{{user_id}}
Content-Type: application/json

###

POST {{server}}/api/auth
Content-Type: application/json

{
  "email": "john doe",
  "password": "12345"
}

### END USER ENDPOINT TESTING